# Numpy Practice

In [5]:
#Importing the necessary libraries
import numpy as np
from time import process_time

In [22]:
#Creating a list to check the time required to perform an operation

list1 = [x for x in range(10000000)]
start_time= process_time()
list1=[x+5 for x in list1]
end_time=process_time()
print("Start Time= {} \nEnd Time= {} \nTime Taken= {} ".format(start_time,end_time, round(end_time-start_time,6)))

Start Time= 1.125 
End Time= 2.21875 
Time Taken= 1.09375 


In [31]:
#Creating a numpy array to check the time required to perform the same operation

np_array= np.array([x for x in range(10000000)])
np_start_time=process_time()
np_array=np_array+int(5)
np_end_time=process_time()
print("Start Time {} \nEnd Time {}\nTime Taken {}".format(np_start_time,np_end_time,np_end_time-np_start_time))

Start Time 8.78125 
End Time 8.78125
Time Taken 0.0


Through the above output we can conclude that performaing mathematical operations on numpy array is faster than that of traditional list

#### Declaring Numpy Array

In [33]:
#Declaring a list in traditional python 
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [34]:
#Declaring a numpy array 
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Through the above excersice we see that the elements in traditional python list are sepearted by comma whereas in a numpy array the elements are seperated by spaces 

#### Shape Function

In [38]:
#declaring a one dimentional numpy array
np_array=np.array([1,2,3,4,5])
np_array.shape

(5,)

In [39]:
#creating a two dimentional numpy array
np_array=np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(np_array)
np_array.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [42]:
#creating a two dimentional numpy array with datatype as float
np_array=np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(np_array)
np_array.shape

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


(2, 5)

#### Initial Placeholders

In [46]:
#creating a numpy array with initial values as zeros
np_array=np.zeros((2,2))
print(np_array)

[[0. 0.]
 [0. 0.]]


In [47]:
#Creating a numpy array with initial values as ones
np_array=np.ones((3,3))
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
#Creating a value with a particular value
np_array=np.full((3,3),5)
print(np_array)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [49]:
#Creating an Identity matrix of particular dimention
np_array=np.eye(3)
print(np_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#creating a numpy array with random values
np_array=np.random.random((3,3))
print(np_array)

[[0.92685045 0.59731292 0.41531515]
 [0.94520677 0.94367205 0.1580501 ]
 [0.39947169 0.76894575 0.20108771]]


In [52]:
#creating a numpy array with random integers
np_array=np.random.randint(1,100,(3,3))
print(np_array)

[[92 49 76]
 [95 45 40]
 [ 6  4 27]]


In [54]:
#creating an array of evenly spaced values (Specifying the number of elements)
np_array=np.linspace(10,30,6)
print(np_array)

[10. 14. 18. 22. 26. 30.]


In [56]:
#creating an array of evenly spaced values (Specifying the size of step)
np_array=np.arange(10,30,5)
print(np_array)

[10 15 20 25]


In [57]:
#Converting a list to numpy array
list1=[1,2,3,4,5]
np_array=np.array(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

#### Analysing Numpy Array

In [63]:
#Creating an array of random numbers between 1 to 100 
np_array=np.random.randint(1,100,(5,5))
print(np_array)

[[67 68 38 40 11]
 [ 4 23 51 11 63]
 [25 59 35 61 46]
 [91 99 92 24  3]
 [34 90 83 86 42]]


In [64]:
#displaying number of columns and rows
np_array.shape

(5, 5)

In [65]:
#displaying dimentions of array
np_array.ndim

2

In [66]:
#displaying the number of elements present in an array
np_array.size

25

In [67]:
#displaying the datatype of elements present in an array
np_array.dtype

dtype('int32')

#### Mathematical Functions

In [69]:
np_array_1=np.random.randint(1,100,(3,3))
np_array_2=np.random.randint(1,100,(3,3))

print("Array 1\n{} \nArray 2\n{}".format(np_array_1,np_array_2))

Array 1
[[88 81 32]
 [63  7  9]
 [89  3 71]] 
Array 2
[[74 39 17]
 [24 13 44]
 [21  9 21]]


In [79]:
#Mathematical Operations

#Addition
print("\nAddition Result\n",np_array_1+np_array_2)

#Subtraction
print("\nSubtraction Result\n",np_array_1-np_array_2)

#Multiplication
print("\nMultiplication Result\n",np_array_1*np_array_2)

#Division 
print("\nDivision Result\n",np_array_1/np_array_2)



Addition Result
 [[162 120  49]
 [ 87  20  53]
 [110  12  92]]

Subtraction Result
 [[ 14  42  15]
 [ 39  -6 -35]
 [ 68  -6  50]]

Multiplication Result
 [[6512 3159  544]
 [1512   91  396]
 [1869   27 1491]]

Division Result
 [[1.18918919 2.07692308 1.88235294]
 [2.625      0.53846154 0.20454545]
 [4.23809524 0.33333333 3.38095238]]


In [78]:
#Mathematical Operations Using Functions

#Addition
print("\nAddition Result\n",np.add(np_array_1,np_array_2))

#Subtraction
print("\nSubtraction Result\n",np.subtract(np_array_1,np_array_2))

#Multiplication
print("\nMultiplication Result\n",np.multiply(np_array_1,np_array_2))

#Division
print("\nDivision Result\n",np.divide(np_array_1,np_array_2))


Addition Result
 [[162 120  49]
 [ 87  20  53]
 [110  12  92]]

Subtraction Result
 [[ 14  42  15]
 [ 39  -6 -35]
 [ 68  -6  50]]

Multiplication Result
 [[6512 3159  544]
 [1512   91  396]
 [1869   27 1491]]

Division Result
 [[1.18918919 2.07692308 1.88235294]
 [2.625      0.53846154 0.20454545]
 [4.23809524 0.33333333 3.38095238]]


#### Array Manipulation

In [81]:
#Creating a numpy array
np_array=np.random.randint(1,100,(2,3))
print(np_array)
np_array.shape

[[71 69 15]
 [38 87 93]]


(2, 3)

In [82]:
#Creating a transpose of np_array
np_array_transpose=np.transpose(np_array)
print(np_array_transpose)
np_array_transpose.shape

[[71 38]
 [69 87]
 [15 93]]


(3, 2)

In [84]:
#Method 2 : Finding Transpose (With .T )
np_array_transpose_2=np_array.T
print(np_array_transpose_2)
np_array_transpose_2.shape

[[71 38]
 [69 87]
 [15 93]]


(3, 2)

In [86]:
#reshape an array
np_array_reshaped=np.reshape(np_array,(3,2))
print(np_array_reshaped)
np_array_reshaped.shape

[[71 69]
 [15 38]
 [87 93]]


(3, 2)